### PR TITLE
feat: Refactor & Add Edit Subject Functionality

### LINKED ISSUE #2: [FEAT] Add / Edit Subject Page
**Is your feature request related to a problem? Please describe.**
The page for creating or editing subjects isn't there yet.

**Describe the solution you'd like**
- User should be able to create Subject in his collection
- User should be able to edit the subject info
- Subject contains Name, Days, Credits
- No need to change the widget AppBar. A new issue is there for it.

Bonus: Add Location of class as current location. If it seems hard, it will be created as a new issue don't worry

**Describe alternatives you've considered**
UI is not fixed. You have liberty to edit the UI

**Additional context**
Rough wireframe of UI:
 
image

Full Figma: https://www.figma.com/design/SSqE8Fn9qAakayjyhZ9gqf/Attendance-Tracker?node-id=0-1&t=Xpgi43pHobRh2dnD-1

### PR DESCRIPTION
**Pull request by criticic**
### Description

Sorry for the delay though. Refactored the code to move the edit/create subject dialogue to another file, and implemented the edit subject feature

### Related Issue

Fixes #2 

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update

### Screenshots (if any):

Please add screenshots to be easily reviewable

### Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by criticic** [comment]
not sure why the two tests are failing

**Comment by Varun-Kolanu** [comment]
> not sure why the two tests are failing

Yeah that's okay label-pr and android-build kisika nhi ho rha tha 
Abhi mann bhi nhi hai unko change karne ka

I too am not sure why commut-style is failing

**Comment by Varun-Kolanu** [comment]
@criticic Nice one. 
But not sure why the Grade and Marks are not being rendered. Can you look into that?

**Comment by criticic** [comment]
fixed it!

**Comment by Varun-Kolanu** [comment]
Cool

Thanks for the PR!

**Pull request merged**
