### PR TITLE
feat: Added Navigation Sidebar

### LINKED ISSUE #8: [FEAT] Sidebar
**Describe the solution you'd like**
- A beautiful Sidebar
- Including animation to slide in and out

**Additional context**
UI and features in sidebar:

image

Full Figma: [Figma](https://www.figma.com/design/SSqE8Fn9qAakayjyhZ9gqf/Attendance-Tracker?node-id=0-1&t=Xpgi43pHobRh2dnD-1)

### PR DESCRIPTION
**Pull request by Rasesh2005**
### Description

Added a sidebar according to requirements of the issue.

### Related Issue

Fixes #8 

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update

### Screenshots (if any):
Added notification bell at top right section instead of side bar.. and fired the overflow by ending the text with...(Do tell me if there's a better solution)
Screenshot 2024-06-10 at 11 59 10 PM

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Varun-Kolanu** [comment]
Nice Looking great!

Due to the merging of another PR, your PR has some conflicts. Please resolve accordingly.

And a suggestion, if possible, isolate the side bar as another widget because it might be used in many places in the app

**Comment by Rasesh2005** [comment]
I did make a seperate widget.. should I place it in a new file or ?? and yeah.. will resolve the conflict

**Comment by Rasesh2005** [comment]
I made a seperate class within home page only. for navigationBar.. should I make a seperate file and put it in there??

**Comment by Varun-Kolanu** [comment]
> I made a seperate class within home page only. for navigationBar.. should I make a seperate file and put it in there??

Yeah it would be better if it is put in widgets folder

**Comment by Varun-Kolanu** [comment]
@Rasesh2005 I'll make the issue a medium one

Also add some dummy page and make the app navigate it to that page when clicked on a tile in sidebar

**Comment by Rasesh2005** [comment]
will be making a new PR as too many commits have been made after this change..

**Comment by Varun-Kolanu** [comment]
> will be making a new PR as too many commits have been made after this change..

Yeah no problems go ahead

**Comment by Rasesh2005** [comment]
@Varun-Kolanu One Suggestion please, Should I use the same appBar everywhere or should I add a back button on every page so that we can go to every page only from home screen?? (Should not make a difference since I am only making a dummy page but still :) )

**Pull request closed without merging**
